- coveragerc
- relengapi/lib/apidoc.py
- relengapi/lib/auth/__init__.py
- relengapi/tests/test_lib_auth.py
- relengapi/tests/test_lib_auth_external.py
- validate.sh
I was bored..
And yes. the apidoc bit is probably cheating, but I barely understand how docutils works, let alone how to test it.  Besides, the code is exercised by building the docs, and anyway it's not production code.
> Get better coverage

- README.md
- docs/deployment/@relengapi/index.rst
- docs/deployment/@relengapi/installation.rst
@jvehent - let me know if there are more than this!
> Describe the devel packages you need to build a virtualenv

- relengapi/lib/aws.py
- relengapi/tests/test_lib_aws.py
The typical boto.connect_s3 method doesn't take a 'region' argument like
most of the others, so we use boto.s3.connect_to_region instead.
> Add special case for connecting to S3

- docs/usage/@relengapi/tokenauth.rst
- docs/usage/@relengapi/using.rst
- relengapi/blueprints/tokenauth/loader.py
- relengapi/blueprints/tokenauth/test_loader.py
> HTTP header with authentication data is called "Authorization"

- relengapi/blueprints/tokenauth/static/tokens.html
> include an example of a token description

- docs/development/@relengapi/app.rst
- docs/development/@relengapi/web-ui.rst
https://api.pub.build.mozilla.org/docs/development/@relengapi/app/ probably doesn't list everything it should.
> Make sure "Flask App" docs include all app attributes

- relengapi/blueprints/tokenauth/__init__.py
- relengapi/blueprints/tokenauth/test_usermonitor.py
- relengapi/blueprints/tokenauth/usermonitor.py
This adds the logging mentioned in #163.
> Add logging of token creation and revocation

- docs/deployment/@relengapi/config.rst
- relengapi/lib/celery.py
- relengapi/tests/test_lib_celery.py
#179, but with tests and docs.  r? @Callek?
> Celery logging

- docs/development/@relengapi/databases.rst
- relengapi/blueprints/base/__init__.py
I found this useful, and it doesn't hurt.
> Add 'relengapi repl' for debugging use

- validate.sh
Travis sets a few environment variables, so we can tell when we're in travis:
```
TRAVIS_JOB_ID=25905243
```
and in that case, issuing lines like
```
travis_fold:start:something
...
travis_fold:end:something
```
will fold the contained contents down to a single line.
> Fold validate.sh output in Travis

- relengapi/blueprints/tokenauth/static/tokens.js
fix for https://github.com/mozilla/build-relengapi/issues/198
> dont show orange revoke tokens button if there are no revokable tokens

- relengapi/blueprints/badpenny/__init__.py
- relengapi/blueprints/badpenny/static/badpenny.css
- relengapi/blueprints/badpenny/static/badpenny.html
- relengapi/blueprints/badpenny/static/badpenny.js
- relengapi/blueprints/badpenny/static/bp-job.html
- relengapi/blueprints/badpenny/static/bp-task.html
- relengapi/blueprints/badpenny/test_badpenny.py
For testing and probably a lot of other reasons, it'd be nice to be able to manually trigger a run of a badpenny task.
This should be a single new API method, protected by a new permission.
> API method to force a run of a badpenny task

- relengapi/lib/db.py
> Revert setting MySQL timezone to UTC

- relengapi/lib/testing/context.py
This fixes the tooltool build failure in https://travis-ci.org/djmitche/build-tooltool/jobs/61779980
> Use the correct function signature for fake test_client.open

- relengapi/templates/layout.html
This was a minor nit I noticed while looking in my IDE...
r? @djmitche
> Fix mistyped HTML comment

- CONTRIBUTING.rst
- MANIFEST.in
- relengapi/docs/development/blueprints.rst
- relengapi/docs/development/contributing.rst
- relengapi/docs/development/index.rst
This adds contribution guidelines, and also gets rid of the stuff talking about the skeleton.
> Bug 1171004: Docs overhaul

- relengapi/blueprints/mapper/__init__.py
- relengapi/docs/usage/mapper.rst
> Add mapper documentation from wiki and docstrings

- relengapi/blueprints/slaveloan/static/slaveloan_root.html
This fixes a mistakenly not pushed piece of the CSS for the main page.
r? @djmitche
> Add form-horizontal CSS to form

- relengapi/lib/testing/context.py
A small improvement I made while working on tree status
> Add reason to testing response logging

- relengapi/docs/development/http.rst
- relengapi/docs/development/index.rst
- relengapi/lib/http.py
- relengapi/tests/test_lib_http.py
Another useful bit I found while porting treestatus
> support adding response headers with a decorator

- relengapi/docs/deployment/badpenny.rst
- relengapi/docs/deployment/workers.rst
- relengapi/lib/celery.py
- relengapi/tests/test_lib_celery.py
@lundjordan what do you think?
> Run celery.backend_cleanup via Badpenny

- relengapi/blueprints/base/__init__.py
- relengapi/blueprints/base/test_base.py
- validate.sh
@acmiyaguchi 
This just makes validate a little nicer, and allows me (and anyone with a MySQL instance) to run the MySQL tests locally, rather than waiting for Travis.
> Icing on the Alembic Cake

- validate.sh
This fixes a bug dealing with offline migration tests. Downgrades offline do not allow for incremental changes using relative values, ie we cant go from `<head>:<head-1>`, and then from `<head-1>:<head-2>`. This will apply a full downgrade and a full upgrade, but through the alembic mechanism rather than from bash.
> [alembic] Apply full downgrade and upgrades to db migrations in validation.sh

- relengapi/blueprints/mapper/__init__.py
- relengapi/blueprints/mapper/test_mapper.py
- relengapi/docs/usage/mapper.rst
https://bugzil.la/1174215 has details
> Bug 1174215: Add endpoint to return all configured project names

- relengapi/blueprints/treestatus/model.py
- relengapi/blueprints/treestatus/test_treestatus.py
- relengapi/tests/test_column_types.py
..and add some tests so nobody makes the same mistake again!
> Use UTCDateTime for treestatus

- validate.sh
@Callek - the `-rc .` was picking up my virtualenv, and that has lots of unsorted files in it :)
> Only isort relengapi/

- setup.py
This works around issue#340 to get new PR's passing again
> Lock Flask-Login version to work around issue #340

- relengapi/blueprints/base/__init__.py
So in both badpenny code and archiver code we use logger.bind, that seems to leak the binding outside of the scope you intend, e.g.:
```
-------------------- >> begin captured logging << --------------------
relengapi.blueprints.slaveloan.bugzilla: WARNING: No bugzilla user specified. (Set BUGZILLA_USER in config to fix) (task_id='a321
e6a9-0e45-4655-bb55-707f3b9bd5b8' task_name='relengapi.blueprints.badpenny.execution._run_job' request_id='a5267d58-4e94-40ab-83f
a-eba015fa9f80' archiver_task_state='STARTED' archiver_task=u'foo' user='anonymous:')
relengapi.blueprints.slaveloan.bugzilla: WARNING: No bugzilla password specified. (Set BUGZILLA_PASS in config to fix) (task_id='
a321e6a9-0e45-4655-bb55-707f3b9bd5b8' task_name='relengapi.blueprints.badpenny.execution._run_job' …
```
> logger.bind bleeds to other modules/scopes

- relengapi/blueprints/tooltool/__init__.py
- relengapi/lib/auth/__init__.py
- relengapi/lib/permissions.py
- relengapi/templates/layout.html
- relengapi/tests/test_lib_auth.py
- relengapi/tests/test_lib_permissions.py
- setup.py
Discovered on Flask-Login's 0.3.0 release today, and some slaveloan tests
> Flask-Login 0.3 has breaking changes over 0.2.11

- relengapi/docs/conf.py
Stop confusing people by nature of having an empty index.
> Mask issue #157 by not displaying index or module links

- relengapi/app.py
- relengapi/templates/robots.txt
- relengapi/tests/test_app.py
> Add a robots.txt

- relengapi/blueprints/mapper/__init__.py
@hwine do you want to have a look?
> Bug 1204758: stream mapfiles rather than building them in memory

- README.md
Updated readme for : https://github.com/mozilla/build-relengapi/issues/363
> Updated command for building docs in README.md file

- relengapi/blueprints/clobberer/static/clobberer.js
I just want to see Travis run here..
> remove un-detected merge conflicts

- relengapi/blueprints/treestatus/__init__.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/build-relengapi/382)
> treestatus: adding redirect for details page

- relengapi/blueprints/archiver/tables.py
- relengapi/blueprints/archiver/test_archiver.py
- settings_example.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/build-relengapi/385)
> archiver: renaming tables and using its own connection

- relengapi/blueprints/tooltool/__init__.py
- relengapi/blueprints/tooltool/grooming.py
- relengapi/blueprints/tooltool/tables.py
- relengapi/blueprints/tooltool/test_grooming.py
- relengapi/blueprints/tooltool/test_tables.py
- relengapi/blueprints/tooltool/test_tooltool.py
- settings_example.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla/build-relengapi/386)
> tooltool: tables rename and using tootool session
