- docs/development/@relengapi/blueprints.rst
- relengapi/app.py
- relengapi/lib/introspection.py
- relengapi/tests/test_lib_introspection.py
- setup.cfg
- setup.py
When a dist is installed, its `setup.cfg` is no longer available.  So all of the handy `relengapi_metadata` in there is no longer available.  Apparently this is just hard!!
> relengapi_metadata is not installed

- relengapi/blueprints/badpenny/cleanup.py
- relengapi/blueprints/badpenny/tables.py
- relengapi/blueprints/badpenny/test_badpenny.py
- relengapi/blueprints/docs/test_docs.py
- relengapi/lib/db.py
```
IntegrityError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (IntegrityError) (1451, 'Cannot delete or update a parent row: a foreign key constraint fails (`relengapi`.`badpenny_job_logs`, CONSTRAINT `badpenny_job_logs_ibfk_1` FOREIGN KEY (`id`) REFERENCES `badpenny_jobs` (`id`))') 'DELETE FROM badpenny_jobs WHERE badpenny_jobs.id = %s' ((1235L,), (1238L,), (1240L,), (1243L,), (1245L,), (1248L,), (1250L,), (1253L,)  ... displaying 10 of 14 total bound parameter sets ...  (1265L,), (1268L,))
[2015-03-18 11:19:27,045: ERROR/Worker-2] Job 1276 failed
```
> badpenny `cleanup_old_jobs` fails with integrity error

- docs/conf.py
Since we present docs inline using Jinja2 templates, this doesn't
actually have much effect, but it silences a warning from sphinx.
> Use the 'classic' sphinx theme

- relengapi/lib/db.py
- relengapi/tests/test_lib_celery.py
Sessions are currently scoped per app instance, which means that a failed transaction in one celery task will "poison" all of the subsequent tasks.
> Reset DB sessions between celery tasks

- docs/development/@relengapi/app.rst
- docs/development/@relengapi/auth.rst
- docs/usage/@relengapi/tokenauth.rst
- relengapi/blueprints/tokenauth/__init__.py
- relengapi/blueprints/tokenauth/loader.py
- relengapi/blueprints/tokenauth/static/tokens.html
- relengapi/blueprints/tokenauth/tables.py
- relengapi/blueprints/tokenauth/test_loader.py
- relengapi/blueprints/tokenauth/test_tokenauth.py
- relengapi/blueprints/tokenauth/test_usermonitor.py
- relengapi/blueprints/tokenauth/types.py
- relengapi/blueprints/tokenauth/usermonitor.py
- relengapi/blueprints/tokenauth/util.py
- relengapi/lib/auth/base.py
- relengapi/lib/auth/ldap_group_authz.py
- relengapi/lib/auth/static_authz.py
- relengapi/tests/test_lib_auth_ldap_group_authz.py
- relengapi/tests/test_lib_auth_static_authz.py
@callek, @jvehent 
This, along with #175, should finish off the user-token work described in #163.
> Disable user tokens

- docs/development/@relengapi/index.rst
- docs/development/@relengapi/safety.rst
- relengapi/lib/auth/__init__.py
- relengapi/lib/auth/external.py
- relengapi/lib/safety.py
- relengapi/tests/test_lib_safety.py
I'm open to other ideas for module name beyond 'safety'.  But I figure we'll end up with a half-dozen random utility functions, similar to [Werkzeug](http://werkzeug.pocoo.org/docs/0.10/utils/)
> prohibit open redirects

- relengapi/blueprints/tokenauth/static/tokens.js
- relengapi/static/js/relengapi.js
It appears that `[].slice.apply` is the normal way to do this anyway.
> fix JS usage on chrome

- relengapi/lib/aws.py
- relengapi/tests/test_lib_aws.py
I wonder if there's some race condition with moto and the threading, where we sometimes make calls to the "real" SQS.  The bogus certificate in this error looks very strange, though.
```
Exception in thread us-east-1/'my-sqs-queue' -> <function listener at 0x7ffe0f72ec08>:
Traceback (most recent call last):
File "/opt/python/2.7.9/lib/python2.7/threading.py", line 810, in __bootstrap_inner
self.run()
File "/opt/python/2.7.9/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/home/travis/build/mozilla/build-relengapi/relengapi/lib/aws.py", line 92, in _listen_thd
msg = queue.read(wait_time_seconds=20, **read_args)
File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/boto/sqs/queue.py", line 208, in read …
```
> SQS tests are flaky

- docs/relnotes/2.0.0.rst
- relengapi/lib/db.py
When running badpenny tasks and updating the job rows:
```
[2015-03-27 18:22:29,935: WARNING/Worker-1] /home/dustin/code/relengapi/t/tooltool/sandbox/lib/python2.7/site-packages/sqlalchemy/engine/default.py:436: Warning: Data truncated for column 'started_at' at row 1
cursor.execute(statement, parameters)
[2015-03-27 18:22:29,940: WARNING/Worker-2] /home/dustin/code/relengapi/t/tooltool/sandbox/lib/python2.7/site-packages/sqlalchemy/engine/default.py:436: Warning: Data truncated for column 'started_at' at row 1
cursor.execute(statement, parameters)
[2015-03-27 18:22:29,980: WARNING/Worker-2] /home/dustin/code/relengapi/t/tooltool/sandbox/lib/python2.7/site-packages/sqlalchemy/engine/default.py:436: Warning: Data truncated for column 'completed_at' at row 1
cursor.execute(statement, …
```
> data truncated for datetime columns

- docs/deployment/@relengapi/environment.rst
- setup.py
If you actually send "Authorization: foo" over HTTP, it doesn't make it to the server the way the tests suggest.
> wsgi/Werkzeug/Flask handle the 'Authorization' header

- relengapi/blueprints/badpenny/execution.py
This avoids creating a lot of result queues that serve no purpose.
> Bug 1151636: ignore results for badpenny tasks

- docs/deployment/@relengapi/config.rst
- relengapi/lib/db.py
- settings_example.py
This solves #48, using @rahulrrixe's commit from #173.
Rahul, what do you think?
> Enable logging of SQL statements

- docs/deployment/@relengapi/config.rst
- relengapi/lib/auth/constant.py
- relengapi/tests/test_lib_auth_constant.py
- setup.py
This is handy when you're not on the 'net and thus browserid is not
practical.
> Implement 'constant' auth

- .travis.yml
- relengapi/lib/subcommands.py
Without this, I have to manually set RELENGAPI_SETTINGS when I switch between blueprints (tooltool vs. clobberer vs. relengapi).  With this, I can just set it to `settings.py` and it will use that file in the cwd.
r?
> allow RELENGAPI_SETTINGS to be relative to the current directory

- relengapi/lib/testing/context.py
So `client.get('/foo/bar')` should log something like
```
test_client: INFO: GET /foo/bar
```
This will require monkey-patching werkzeug a little bit; see https://github.com/mozilla/build-relengapi/blob/master/relengapi/lib/testing/context.py#L85
> During tests, log all paths used with the test client

- docs/development/@relengapi/web-ui.rst
- relengapi/blueprints/auth/static/account.html
- relengapi/blueprints/auth/static/account.js
- relengapi/blueprints/tokenauth/static/permissionSelector.html
- relengapi/blueprints/tokenauth/static/tokens.html
- relengapi/lib/angular.py
- relengapi/lib/permissions.py
- relengapi/static/js/relengapi.js
- relengapi/tests/test_lib_permissions.py
If you hover over a permission anywhere in the Releng API UI, it should give you the description for that permission.
This will require adding an endpoint that describes permissions (probably in the `auth` blueprint), then calling that appropriately from Angular code.
> Improve the <perm> directive to describe permissions in a tooltip

- relengapi/blueprints/tokenauth/__init__.py
- relengapi/blueprints/tokenauth/static/tokens.css
- relengapi/blueprints/tokenauth/static/tokens.html
Mostly a new user issue - it's not obvious that to issue a token, the description must be non-empty.
Having the "issue" button visible, but disabled, would suggest that something more needs to be done.
> On token generation page, "issue" button should be disabled, not hidden

- relengapi/blueprints/tokenauth/loader.py
- relengapi/blueprints/tokenauth/test_loader.py
When authenticating with a token, str(current_user) contains only the token ID, which doesn't indicate *whose* token it is.  That info should be readily avaliable, and would make logging a lot more helpful!
> Format user tokens better

- MANIFEST.in
- contribute.json
This lists github as the repository, even though it's not the RoR.  I
think that will be simpler for contirbutors.
This refs #224.
> Add relengapi contribute.json

- relengapi/lib/db.py
When setting up a MySQL engine or connection, set some extra options:
* storage_engine (defaulting to InnoDB)
* always use unicode
* set timezone = UTC
Buildbot is a good example for the storage engine, at least (although it sets MyISAM).
> Handle extra MySQL engine options

- relengapi/lib/auth/ldap_group_authz.py
- relengapi/tests/test_lib_auth_ldap_group_authz.py
This will enable us to match scm_level_* groups, specifically.
@jdow does this look awful?  @callek, designed review-guy-for-relengapi, what do you think?
> Add support for Mozilla-style POSIX groups

- setup.py
PR #194 broke upgrade attempts due to the lack of a hint to upgrade Sphinx.
In manual testing Sphinx 1.3 is enough to get past the error:
```sphinx.errors.ThemeError: no theme named 'classic' found (missing theme.conf?)```
> Add req of Sphinx>=1.3

- relengapi/blueprints/tokenauth/static/tokens.html
- relengapi/templates/login_request.html
As it is, if you can't issue or view tokens, you get a big 'ol blank screen, which leads to lots of "[what browser version are you using](https://bugzilla.mozilla.org/show_bug.cgi?id=1162556)" kind of debugging.
> When !can_view and !can_issue, tokenauth view should show *something*

- relengapi/blueprints/badpenny/cleanup.py
- relengapi/blueprints/badpenny/static/badpenny.js
- relengapi/blueprints/badpenny/test_badpenny.py
The existing code assumed that tasks were returned in the order they were created, and the tests did nothing to dissuade them (one of the downsides of testing with SQLite).  I bulked up the test a little bit, and refactored the filtering to go job-by-job rather than loading everything into a list, since 7 days of once-a-minute jobs could start to be a lot of RAM.
> Bug 1173648: fix display, cleanup of badpenny tasks

- relengapi/docs/deployment/logging.rst
Logging is configured outside of RelengAPI, but that's tricky to do with celery.  So best to document it.
> Bug 1175411: Add docs for configuring logging

- relengapi/blueprints/tooltool/__init__.py
- relengapi/blueprints/tooltool/test_tooltool.py
This avoids some ISEs on manifests that lack visibilities
> Verify visibilities are set for uploads

- relengapi/blueprints/tokenauth/types.py
Technically an API change, but that field is never used for input or output.
> remove unused client_d

- relengapi/blueprints/tokenauth/loader.py
- relengapi/blueprints/tokenauth/test_loader.py
Failing instead of silently succeeding gives users a better indication of an issue with their credentials.
This will break @mrrrgn's try runs which use "TODO" as a token.  That will need some modification in mozharness, etc. before this lands.
> If an authorization header is present, use it or fail

- relengapi/docs/development/blueprints.rst
The sample test script includes a bunch of badpenny unnecessarily.
> Clean up building-a-blueprint docs

- relengapi/blueprints/tooltool/static/tt-result-file.html
- relengapi/blueprints/tooltool/tables.py
- relengapi/blueprints/tooltool/test_tooltool.py
- relengapi/blueprints/tooltool/types.py
The tooltool page exposes the download link to files with nonexistent instances. This pr disables the download link link so you aren't redirected to a broken link, which  could be the result of removed instances or incomplete file uploads.
> [cosmetic] Disable download link in tooltool if there are no active file instances

- relengapi/blueprints/archiver/__init__.py
- setup.py
quick typo fix in logging. forgive me if I should have asked for a review on this before landing
> bug 1182532 - log task_id not the sql gen id when deleting archiver tracker tasks

- relengapi/docs/development/api_methods.rst
- relengapi/lib/api.py
- relengapi/tests/test_lib_api.py
Regular old `json.dumps` will barf on a WSME type; and `json.loads` will successfully load such a thing, but represent it as a dictionary rather than a WSME object.  These little gems take care of both problems.
> add api.loads and api.dumps

- relengapi/blueprints/archiver/__init__.py
I can't use task now that we moved it outside the block it was created. we know what the task id is though as we define it in task_id already
> fixes typo where task id was referenced before use

- relengapi/app.py
- relengapi/blueprints/treestatus/__init__.py
- relengapi/blueprints/treestatus/model.py
- relengapi/blueprints/treestatus/static/footer.html
- relengapi/blueprints/treestatus/static/index.html
- relengapi/blueprints/treestatus/static/tree.html
- relengapi/blueprints/treestatus/static/treeStatusControl.html
- relengapi/blueprints/treestatus/static/treestatus.css
- relengapi/blueprints/treestatus/static/treestatus.js
- relengapi/blueprints/treestatus/test_treestatus.py
- relengapi/blueprints/treestatus/types.py
- relengapi/docs/usage/index.rst
- relengapi/docs/usage/treestatus.rst
This makes some pretty substantial changes to the sheriff/admin UIs, but is largely the same for users.
Functionally, a big difference here is that trees are no longer removed from outstanding changes if an update is made with the "remember" checkbox unchecked.  That allows the common workflow of closing trees with reason "OMG!", then later following up with a new reason ("bug 1234") without remembering the latter change.  When the first change is undone, the status returns to what it was before.
The DB changes quite a bit, too -- new table names, column names, and column types.  Transitioning from one to the other shouldn't be too hard, though - a decent mysqldump should do the trick.  We'll also need to change the hghook to point at a different URL.  I had a look at the hook already, …
> Port Treestatus

- relengapi/blueprints/treestatus/__init__.py
- relengapi/blueprints/treestatus/test_treestatus.py
- relengapi/docs/usage/treestatus.rst
- setup.py
This is part of the deployment strategy: proxy requests from the old treestatus URL to the new.  But RelengAPI wraps every API response in {'result': ..}, while the old treestatus did not.
> Add compat endpoints for compatibility with old treestatus

- relengapi/lib/celery.py
This warning is kind of silly -- if you're exposing your celery queue to malicious data, you're already doing it wrong, pickle or not.  So we should silence this in code by setting `CELERY_ACCEPT_CONTENT` if it's not already set.
```
[2015-06-18 10:36:30,016: WARNING/MainProcess] /data/www/relengapi/virtualenv/lib/python2.7/site-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.
The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.
If you depend on pickle then you should set a …
```
> Set `CELERY_ACCEPT_CONTENT` if it's not already set

- relengapi/app.py
- relengapi/blueprints/badpenny/__init__.py
- relengapi/blueprints/clobberer/__init__.py
- relengapi/blueprints/clobberer/test_api.py
- relengapi/blueprints/mapper/__init__.py
- relengapi/blueprints/mapper/test_mapper.py
- relengapi/blueprints/slaveloan/__init__.py
- relengapi/blueprints/tokenauth/__init__.py
- relengapi/blueprints/tokenauth/loader.py
- relengapi/blueprints/tokenauth/tables.py
- relengapi/blueprints/tokenauth/test_loader.py
- relengapi/blueprints/tokenauth/test_tokenauth.py
- relengapi/blueprints/tokenauth/test_usermonitor.py
- relengapi/blueprints/tokenauth/util.py
- relengapi/blueprints/treestatus/__init__.py
- relengapi/blueprints/treestatus/test_treestatus.py
- relengapi/docs/development/api_methods.rst
- relengapi/docs/development/auth.rst
- relengapi/docs/development/blueprints.rst
- relengapi/lib/angular.py
- relengapi/lib/auth/perms_types/ldap_groups.py
- relengapi/lib/auth/perms_types/static.py
- relengapi/tests/test_lib_auth.py
- relengapi/tests/test_lib_auth_perms_types_ldap_groups.py
- relengapi/tests/test_lib_auth_perms_types_static.py
`relengapi` used to be a namespace package, which meant it couldn't have attributes at import time, and they were added only later when `relengapi.app` was imported.
It's no longer a namespace package, so this is no longer required.
> Make `relengapi.apimethod`, etc. exist when importing `relengapi`

- relengapi/blueprints/badpenny/execution.py
- relengapi/blueprints/badpenny/test_badpenny.py
- relengapi/lib/badpenny.py
```
[2015-07-29 10:20:05,306: ERROR/Worker-1] Job 53 failed
Traceback (most recent call last):
File "/home/dustin/code/relengapi/t/relengapi/relengapi/blueprints/badpenny/execution.py", line 69, in _run_job
task.task_func(job_status)
File "/home/dustin/code/relengapi/t/relengapi/relengapi/lib/celery.py", line 29, in __call__
return TaskBase.__call__(self, *args, **kwargs)
File "/home/dustin/code/relengapi/t/relengapi/sandbox/lib/python2.7/site-packages/celery/app/trace.py", line 439, in __protected_call__
return orig(self, *args, **kwargs)
File "/home/dustin/code/relengapi/t/relengapi/sandbox/lib/python2.7/site-packages/celery/app/task.py", line 420, in __call__
return self.run(*args, **kwargs)
TypeError: backend_cleanup() takes no arguments (1 given)
[2015-07-29 10:20:05,310: …
```
> Badpenny execution fails when calling the task fails

- relengapi/blueprints/treestatus/static/treestatus.css
These were likely lost accidentally while deleting a slew of unused CSS
rules.
> Add tree status colors

- relengapi/blueprints/treestatus/static/tree.html
- relengapi/blueprints/treestatus/static/treestatus.css
Not sure why I didn't notice this before, but the table cell was running
into its neighbors, making it difficult to read.  This adds a little
more breathing room, and moves the timezone (UTC) up to the header so
it's not repeated on every line.
> Make the tree log time a little easier to read

- relengapi/lib/db.py
This will at least catch the case where the client charset is `latin1`.
(the PR will reduce coverage since we don't test against MySQL in Travis)
> Set and verify MySQL connection charset

- relengapi/tests/test_lib_aws.py
- setup.py
> test_sqs_listen fails with moto==0.4.11

- relengapi/blueprints/docs/__init__.py
This avoids
```
[Tue Sep 01 21:47:02 2015] [error] 2015-09-01 21:47:02,510 [sqlalchemy.pool.NullPool] Exception during reset or similar
[Tue Sep 01 21:47:02 2015] [error] Traceback (most recent call last):
[Tue Sep 01 21:47:02 2015] [error]   File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 631, in _finalize_fairy
[Tue Sep 01 21:47:02 2015] [error]     fairy._reset(pool)
[Tue Sep 01 21:47:02 2015] [error]   File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 765, in _reset
[Tue Sep 01 21:47:02 2015] [error]     pool._dialect.do_rollback(self)
[Tue Sep 01 21:47:02 2015] [error]   File "/data/www/relengapi/virtualenv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 412, in do_rollback
[Tue Sep 01 …
```
> Use a null StorageBackend to avoid SQLite errors

- relengapi/blueprints/treestatus/__init__.py
- relengapi/blueprints/treestatus/static/treestatus.js
- relengapi/blueprints/treestatus/test_treestatus.py
For example, `REVERT` is not a standard verb.
> Use real HTTP verbs in treestatus

- relengapi/blueprints/tokenauth/__init__.py
- relengapi/blueprints/tokenauth/usermonitor.py
- relengapi/blueprints/tooltool/__init__.py
- relengapi/blueprints/tooltool/grooming.py
- relengapi/lib/logging.py
- relengapi/tests/test_lib_logging.py
- setup.py
This switches things around substantially: non-mozdef output is now
not JSON encoded, so it will be easier to read, and only messages tagged
with `mozdef=True` will be sent to mozdef.  This is currently limited to
tooltool and tokenauth.
> Bug 1192021: log directly to mozdef, rather than via syslog

- relengapi/blueprints/slaveloan/__init__.py
- relengapi/blueprints/slaveloan/tests/test_slaveloan.py
- relengapi/docs/development/testing.rst
- relengapi/lib/testing/context.py
- relengapi/tests/test_lib_permissions.py
This is to solve https://github.com/maxcountryman/flask-login/commit/2fc6a7e06b560233eadb44f8eba74e2a1bce88be on our local end, and to make sure that tests which care to verify that login is required will be able to pass accurately.
> Set LOGIN_DISABLED explicitly to False in the test context

- relengapi/lib/apidoc.py
I noticed that docs were getting truncated, e.g.
https://api.pub.build.mozilla.org/docs/usage/tokenauth/#types
> **typ** (*Enum(prm, tmp, usr)*) -- token type (short string). This defaults to `prm` for backward
This patch makes that:
> **typ** (*Enum(prm, tmp, usr)*) -- token type (short string). This defaults to `prm` for backward compatibility, but should always be specified.
There are many other places in the code this is an issue
> Bugfix - AutoType should allow newlines for type comments

- relengapi/docs/usage/mapper.rst
The example URLs were all correct, but the headings were not.
> docs: Some documentation missing '/mapper' prefix

- setup.py
If you run against the lastest mock, it fails because funcsigs isn't installed - see https://github.com/testing-cabal/mock/issues/316.
Easiest fix is to temporarily require funcsigs ourselves.
> mock-1.3.0 install is buggy

- relengapi/blueprints/base/__init__.py
```
Traceback (most recent call last):
File "/data/releng-stage/src/relengapi/virtualenv/bin/relengapi", line 9, in <module>
load_entry_point('relengapi==3.3.0', 'console_scripts', 'relengapi')()
File "/data/releng-stage/src/relengapi/virtualenv/lib/python2.7/site-packages/pkg_resources.py", line 356, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/data/releng-stage/src/relengapi/virtualenv/lib/python2.7/site-packages/pkg_resources.py", line 2439, in load_entry_point
return ep.load()
File "/data/releng-stage/src/relengapi/virtualenv/lib/python2.7/site-packages/pkg_resources.py", line 2155, in load
['__name__'])
File "/data/releng-stage/src/relengapi/virtualenv/lib/python2.7/site-packages/relengapi/cmd.py", line 11, in <module>
import relengapi.app …
```
> Production code shouldn't require nose

- relengapi/blueprints/treestatus/static/treestatus.js
Per https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/replace
flags is deprecated and not supported in V8.
> Replace use of flags in string.replace with a RegExp

- relengapi/blueprints/tokenauth/static/tokens.js
- relengapi/static/js/relengapi.js
I just had to add `headers: {'Content-Type': 'application/json'}` to a restapi request; restapi should do this for me when there is data present.
> restapi Angular service should set Content-Type on requests

- relengapi/blueprints/treestatus/static/index.html
- relengapi/blueprints/treestatus/static/tree.html
This adds an easier-to-click target for getting back to the main treeherder page.
> Bug 1215215 - Add link to main treestatus page to tree page headers

- relengapi/blueprints/tooltool/__init__.py
- relengapi/blueprints/tooltool/test_tooltool.py
Still needs tests; see https://bugzilla.mozilla.org/show_bug.cgi?id=1245170 for the motivation.
> Bug 1245170: Allow tooltool uploads with non-user-associated tokens

- relengapi/blueprints/treestatus/static/treeStatusControl.html
- relengapi/blueprints/treestatus/static/treestatus.js
Not really tested much, but I think this should work. 
The change to treeStatusControl.html should hide the MotD elements on the main treestatus page unless only a single tree is selected selected (it won't show without first selecting a single tree), while still leaving it visible on the individual tree pages.
The change to treestatus.js should prevent mass clobbering if you select a single tree on the main page, type a MotD into the form, then continue to select additional trees before clicking "Update".
I was going to use an ng-if instead of ng-hide, but that seemed to break updating MotDs entirely.
> Bug 1248205 - Don't allow changing the motd for more than one tree at a time

- relengapi/docs/usage/requests-responses.rst
- relengapi/docs/usage/tokenauth.rst
Several places were missing the required ':' for a valid HTTP header.
> Correct Authorization: example HTTP syntax - fixes #377
